version: 2.1
orbs: 
  python: circleci/python@2.2.0
commands:
  pytest-unit:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            pytest tests/unit
          name: pytest unit
  pylint:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            pylint changelog_manager
          name: pylint
  safety:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            safety scan
          name: safety
  bandit:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            bandit changelog_manager -lll
          name: bandit

jobs:
  tests-pylint-3-12:
    docker: 
      - image: cimg/python:3.12
    steps:
      - pylint
  tests-pylint-3-11:
    docker: 
      - image: cimg/python:3.11
    steps:
      - pylint
  tests-pylint-3-10:
    docker: 
      - image: cimg/python:3.10
    steps:
      - pylint
  tests-pylint-3-9:
    docker: 
      - image: cimg/python:3.9
    steps:
      - pylint


  tests-safety-3-12:
    docker: 
      - image: cimg/python:3.12
    steps:
      - safety
  tests-safety-3-11:
    docker: 
      - image: cimg/python:3.11
    steps:
      - safety
  tests-safety-3-10:
    docker: 
      - image: cimg/python:3.10
    steps:
      - safety
  tests-safety-3-9:
    docker: 
      - image: cimg/python:3.9
    steps:
      - safety


  tests-pytest-unit-3-12:
    docker: 
      - image: cimg/python:3.12
    steps:
      - pytest-unit
  tests-pytest-unit-3-11:
    docker: 
      - image: cimg/python:3.11
    steps:
      - pytest-unit
  tests-pytest-unit-3-10:
    docker: 
      - image: cimg/python:3.10
    steps:
      - pytest-unit
  tests-pytest-unit-3-9:
    docker: 
      - image: cimg/python:3.9
    steps:
      - pytest-unit


  tests-bandit-3-9:
    docker: 
      - image: cimg/python:3.9
    steps:
      - bandit
  tests-bandit-3-10:
    docker: 
      - image: cimg/python:3.10
    steps:
      - bandit
  tests-bandit-3-11:
    docker: 
      - image: cimg/python:3.11
    steps:
      - bandit
  tests-bandit-3-12:
    docker: 
      - image: cimg/python:3.12
    steps:
      - bandit


workflows:
  tests:
    jobs:
      - tests-pytest-unit-3-12
      - tests-pytest-unit-3-11
      - tests-pytest-unit-3-10
      - tests-pytest-unit-3-9
      - tests-safety-3-12
      - tests-safety-3-11
      - tests-safety-3-10
      - tests-safety-3-9
      - tests-pylint-3-12
      - tests-pylint-3-11
      - tests-pylint-3-10
      - tests-pylint-3-9
      - tests-bandit-3-12
      - tests-bandit-3-11
      - tests-bandit-3-10
      - tests-bandit-3-9
